### DISCUSSION TITLE
Converting typography tokens to CSS

### DISCUSSION THREAD

**Discussion by nareshbhatia** [six7/figma-tokens#530] [Q&A] [answered]
I have typography tokens in the Figma plugin similar to this:

```json
{
  "h1": {
    "value": {
      "fontFamily": "{font-family.font-sans}",
      "fontWeight": "{font-weight.light}",
      "lineHeight": "{line-height.h1}",
      "fontSize": "{font-size.h1}",
      "letterSpacing": "{letter-spacing.h1}",
      "paragraphSpacing": "{paragraph-spacing.0}",
      "textCase": "{text-case.none}",
      "textDecoration": "{text-decoration.none}"
    },
    "type": "typography"
  }
}
```

When this gets converted to css by the style dictionary I get a single CSS variable with two objects like this:

```css
--h1: [object Object];
```

What I was expecting was a class like this:

```css
.h1 {
  font-family: var(--font-family-font-sans);
  font-weight: var(--font-weight-medium);
  line-height: var(--line-height-h1);
  font-size: var(--font-size-h1);
  letter-spacing: var(--letter-spacing-h1);
  paragraphSpacing: var(--paragraph-spacing-0);
  textCase: var(--text-case-none);
  textDecoration: var(--text-decoration-none);
}
```

What is the intended output and how can it be used in a CSS selector?
