### ISSUE TITLE
[Question] CSS custom property as a HSL component

### ISSUE THREAD

**Issue by dzintars** [six7/figma-tokens#294]
I am not sure do i want this as a feature at all. And does it makes any sense.
I'm just exploring options of this plugin and the way to define token hierarchy.

Consider such CSS feature:
```css
:root {
  --color-hue-dodgerblue: 215;
  --color-primary-500: hsla(var(--color-hue-dodgerblue, 215), 100%, 50%, 1); 
 }
 
 button {
   background-color: var(--color-primary-500, blue);
 }
 ```
*naming convention could be off*

Would something like that be possible to define with Figma Tokens plugin?

For example at global token set i could define:
```json
{
  "root": {
    "hue": {
      "dodgerblue": {
        "value": "215",
        "description": "Brand color hue",
        "type": "other"
      }
    }
  }
}
```
And in some other (actual) color token set i could use it like:
```json
{
  "primary": {
    "500": {
      "value": "hsla($root.hue.dodgerblue, 100%, 50%, 1)",
      "type": "color"
    }
  }
}
```
But in my early tests seems i can't get it working. So i am not sure is it possible at all and will the plugin be able to create an actual style from the something like that.

I am aware that such approach could be pretty fragile because by changing primary hue, most likely saturation and lightness also should be tweaked which means that there is no huge benefit of extracting hue value into separate token.
