### ISSUE TITLE
Using Figma Tokens with Style Dictionary

### ISSUE THREAD

**Issue by djmtype** [six7/figma-tokens#537]
How do we apply and convert unit type on values? 

I'm using Style Dictionary, and typically, this works without any specified transforms. The following values will each receive `rem` appended to them. 

```
{
  "size": {
    "font": {
      "small" : {
        "value": "0.75",
        "comment": "the small size of the font"
      },
      "medium": {
        "value": "1",
        "comment": "the medium size of the font"
      },
      "large" : {
        "value": "2",
        "comment": "the large size of the font"
      },
      "base"  : {
        "value": "{size.font.medium.value}",
        "comment": "the base size of the font"
      }
    }
  }
}
```

I understand Figma doesn't understand anything but pixel units when it comes to font size. But, if I was to set the `fontSizes.body` as `1 rem` in Figma Tokens, then the other font sizes wouldn't get calculated when referencing `fontSizes.body` as a variable. 

And if I was to use `token-transformer` as an intermediate process, the `value` gets calculated, but it's no longer a string value; instead it's a float. 

Has anyone had success with converting and transforming fontSize to rem values?

**Comment by six7** [comment]
You can just set values as you do in style dictionary without any units. That way your calculations will still work.

**Comment by djmtype** [comment]
@six7 I discovered something afterwards and by accident. Style Dictionary needs `options: { outputReferences: true }`  set in order for it to compile the referenced items – which makes perfect sense. That was partially tripping me up. 

Otherwise, the compilation looked like this: 

```css
:root {
  --font-sizes-h1: 16 * 1 * 1.25 * 1.25 * 1.25 * 1.25 * 1.25;
  --font-sizes-h2: 16 * 1 * 1.25 * 1.25 * 1.25 * 1.25;
  --font-sizes-h3: 16 * 1 * 1.25 * 1.25 * 1.25;
  --font-sizes-h4: 16 * 1 * 1.25 * 1.25;
  --font-sizes-h5: 16 * 1 * 1.25;
  --font-sizes-h6: 16 * 1;
  --font-sizes-body: 16;
  --font-sizes-sm: 16 * 0.85;
  --font-sizes-xs: 16 * 0.65;
}
```

Instead of: 

```
:root {
  --font-sizes-body: 16;
  --font-sizes-xs: var(--font-sizes-body) * 0.65;
  --font-sizes-sm: var(--font-sizes-body) * 0.85;
  --font-sizes-h6: var(--font-sizes-body) * 1;
  --font-sizes-h5: var(--font-sizes-h6) * 1.25;
  --font-sizes-h4: var(--font-sizes-h5) * 1.25;
  --font-sizes-h3: var(--font-sizes-h4) * 1.25;
  --font-sizes-h2: var(--font-sizes-h3) * 1.25;
  --font-sizes-h1: var(--font-sizes-h2) * 1.25;
}
```

## Other half of my question – 

By default, Style Dictionary uses the `size/rem` transform when compiling to css files. As you can see above, (`--font-sizes-body: 16;`), no unit is being appended to `16`. 

---
I pulled this example from Style Dictionary's docs. The `size.font.base` `value` gets automatically appended with `rem`. 

```json
 {
  "size": {
    "font": {
      "base"  : {
        "value": "1"
      },
      "small" : {
        "value": "{size.font.base} * 0.75"
      },
      "medium": {
        "value": "{size.font.base}"
      },
      "large" : {
        "value": "{size.font.base} * 2"
      }
    }
  }
}
```

```css
:root {
  --size-font-base: 1rem;
  --size-font-large: var(--size-font-base) * 2;
  --size-font-medium: var(--size-font-base);
  --size-font-small: var(--size-font-base) * 0.75;
}
```

While in this example, from Figma Tokens, no `rem` unit is being appended to `fontSizes.body` `value`.  

```json
{
  "fontSizes": {
    "body": {
      "value": "1",
      "type": "fontSizes"
    },
    "h1": {
      "value": "{fontSizes.h2} * 1.25",
      "type": "fontSizes"
    },
    "h2": {
      "value": "{fontSizes.h3} * 1.25",
      "type": "fontSizes"
    },
    "h3": {
      "value": "{fontSizes.h4} * 1.25",
      "type": "fontSizes"
    },
    "h4": {
      "value": "{fontSizes.h5} * 1.25",
      "type": "fontSizes"
    },
    "h5": {
      "value": "{fontSizes.h6} * 1.25",
      "type": "fontSizes"
    },
    "h6": {
      "value": "{fontSizes.body} * 1",
      "type": "fontSizes"
    },
    "sm": {
      "value": "{fontSizes.body} * 0.85",
      "type": "fontSizes"
    },
    "xs": {
      "value": "{fontSizes.body} * 0.65",
      "type": "fontSizes"
    }
  }
}
```
```css
:root {
  --font-sizes-body: 1;
  --font-sizes-xs: var(--font-sizes-body) * 0.65;
  --font-sizes-sm: var(--font-sizes-body) * 0.85;
  --font-sizes-h6: var(--font-sizes-body) * 1;
  --font-sizes-h5: var(--font-sizes-h6) * 1.25;
  --font-sizes-h4: var(--font-sizes-h5) * 1.25;
  --font-sizes-h3: var(--font-sizes-h4) * 1.25;
  --font-sizes-h2: var(--font-sizes-h3) * 1.25;
  --font-sizes-h1: var(--font-sizes-h2) * 1.25;
}
```
